### ISSUE TITLE
Add test case for NPE in handleDescribeConfigsResponse due to null pendingTopicMetadata

### ISSUE THREAD

**Issue by cmebarrow** [reaktivity/nukleus-kafka.java#126]
Stack trace is 
```
java.lang.NullPointerException
	at org.reaktivity.nukleus.kafka.internal.stream.NetworkConnectionPool$TopicMetadata.access$1400(NetworkConnectionPool.java:2738)
	at org.reaktivity.nukleus.kafka.internal.stream.NetworkConnectionPool$MetadataConnection.handleDescribeConfigsResponse(NetworkConnectionPool.java:1913)
	at org.reaktivity.nukleus.kafka.internal.stream.NetworkConnectionPool$MetadataConnection.handleResponse(NetworkConnectionPool.java:1870)
	at org.reaktivity.nukleus.kafka.internal.stream.NetworkConnectionPool$AbstractNetworkConnection.handleData(NetworkConnectionPool.java:880)
	at org.reaktivity.nukleus.kafka.internal.stream.NetworkConnectionPool$AbstractNetworkConnection.afterBegin(NetworkConnectionPool.java:779)
	at org.reaktivity.nukleus.kafka.internal.stream.NetworkConnectionPool$AbstractNetworkConnection.handleStream(NetworkConnectionPool.java:749)
	at org.reaktivity.reaktor.internal.router.Source.handleRead(Source.java:235)
	at org.agrona.concurrent.ringbuffer.OneToOneRingBuffer.read(OneToOneRingBuffer.java:198)
	at org.agrona.concurrent.ringbuffer.OneToOneRingBuffer.read(OneToOneRingBuffer.java:157)
	at org.reaktivity.reaktor.internal.router.Source.process(Source.java:158)
	at org.reaktivity.nukleus.Nukleus$Composite.process(Nukleus.java:52)
	at org.reaktivity.nukleus.Nukleus$Composite.process(Nukleus.java:52)
	at org.reaktivity.reaktor.Reaktor$Core.doWork(Reaktor.java:190)
	at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:122)
```
using nukleus-kafka.java version 0.96

This condition probably arose because a metadata offense connection failed, causing us to invalidate metadata and force a refresh of the metadata. That raced with a describeConfigs response coming back on the metadata connection.

**Comment by jfallows** [comment]
`meta` decoder has been refactored, no longer susceptible to this issue.
