### ISSUE TITLE
IndexOutOfBounds on population of brokers for Meta-Data requests

### ISSUE THREAD

**Issue by dpwspoon** [reaktivity/nukleus-kafka.java#21]
```
java.lang.ArrayIndexOutOfBoundsException: 1
	at org.reaktivity.nukleus.kafka.internal.stream.NetworkConnectionPool$TopicMetadata.addBroker(NetworkConnectionPool.java:1366)
	at org.reaktivity.nukleus.kafka.internal.stream.NetworkConnectionPool$MetadataConnection.handleResponse(NetworkConnectionPool.java:1016)
	at org.reaktivity.nukleus.kafka.internal.stream.NetworkConnectionPool$AbstractNetworkConnection.handleData(NetworkConnectionPool.java:568)
	at org.reaktivity.nukleus.kafka.internal.stream.NetworkConnectionPool$AbstractNetworkConnection.afterBegin(NetworkConnectionPool.java:491)
	at org.reaktivity.nukleus.kafka.internal.stream.NetworkConnectionPool$AbstractNetworkConnection.handleStream(NetworkConnectionPool.java:461)
	at org.reaktivity.reaktor.internal.acceptable.Source.handleRead(Source.java:182)
	at org.agrona.concurrent.ringbuffer.OneToOneRingBuffer.read(OneToOneRingBuffer.java:198)
	at org.agrona.concurrent.ringbuffer.OneToOneRingBuffer.read(OneToOneRingBuffer.java:157)
	at org.reaktivity.reaktor.internal.acceptable.Source.process(Source.java:95)
	at org.reaktivity.nukleus.Nukleus$Composite.process(Nukleus.java:52)
	at org.reaktivity.nukleus.Nukleus$Composite.process(Nukleus.java:52)
	at org.reaktivity.nukleus.Nukleus$Composite.process(Nukleus.java:52)
	at org.reaktivity.reaktor.Reaktor.lambda$supplyWorker$0(Reaktor.java:180)
	at org.reaktivity.reaktor.Reaktor$1.doWork(Reaktor.java:116)
	at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:122)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by cmebarrow** [comment]
Should be resolved by https://github.com/reaktivity/nukleus-kafka.java/pull/19

**Comment by cmebarrow** [comment]
@dpwspoon Please close if this is resolved by latest available release
