### ISSUE TITLE
NullPointerException due to race between unsubscribe and offset out of range fetch response

### ISSUE THREAD

**Issue by cmebarrow** [reaktivity/nukleus-kafka.java#85]
```
java.lang.NullPointerException
	at org.reaktivity.nukleus.kafka.internal.stream.NetworkConnectionPool$AbstractFetchConnection.handlePartitionResponseError(NetworkConnectionPool.java:1201)
	at org.reaktivity.nukleus.kafka.internal.stream.FetchResponseDecoder.decodePartitionResponse(FetchResponseDecoder.java:313)
```
This can happen when a user unsubscribes between the sending of a fetch request and receiving a  response which has the offset out of range error code  on one of the partition responses.  In this case we look up the better data in map topicMetadataByName and don't find it because it was removed during the NetworkTopic.detach processing.  We need to guard against the metadata being dull.

**Comment by cmebarrow** [comment]
Fixed in PR #115
